language: python
python:
- '3.8'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv
  -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-firefox
- docker run -d -p4444:4444 selenium/standalone-firefox
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
