language: python
python:
- '3.8'
services:
- docker
addons:
  artifacts:
    paths:
    - $(git ls-files -o |grep .png | tr "\n" ":")
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv
  -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-google
- docker run -d -p4444:4444 selenium/standalone-google
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
