language: python
python:
- '3.8'
services:
  - docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=secret.json
  - secure: NwTXWrmAgQ7RjXM3xcQGkbRtGqpmG/ZwRO+fLqmVZDkW07wjS0iroutKi1/ya9eLq3nNHLMUH8Fn15Qy+HIm8UncdSYbo2y4WS3hsYW1CzVxoe2tpQg2VitZcxJ3/+GAkZ1YkxxIY4cyZhOy14VFlWHFyTMOWGVkQ/p2R1xtVpmKsyqyLvEqwhN9Exi7KfvMnHVtc+SeqSBUmtiwvLzdXfaIP90v6aID8VD5WIjQwm5/IU8MVFHoI/Q0lAMwncgkmmR8sB+2ff8IyW+BvjUHJUMoukWtIv9C0nniKyE5OMexOrZPfc1Kevg9lpDR8DlXWHDp9HPOZRtC9cFz5N6D+H3gqstnubFPhHEtzEhKcLMq1+28BA0bSArKF3/kZYaJn3FuxteYkGYIgtlH0aUh9oJjn+fcoCU8DJPfb8r+o85AjM731WayUA6W3fp3cnvWtOPEP5MPUmGjS3Hzl581LbgndT0yuEbnwEScRMcFWUufDi3zXd5xJZTdUHAYNqXcxFOV0XYfvqyq9brSC5mkZP+ILnbHUNaM9IWj7YbYj/lwhUmWvq/xn0qoKVXLM4DgI+iU5USwKyLtTNrGUi60V1/ruqt4T+Tsakvy4qIqSkuJGkg89i1K+S1o6fm7HH07pntDj1oA8XU50G38dASeanNeea1TfANtaHy87ft2zlM=
  - secure: ZZtNvdl30dJibwXiO+5xujsOaNapJC3SxsvtBAtDjzpfSnQAv4SSnJNJiLsJhD/LkwPPjlXfEbIBTs1VeXUbYF8e0h6lZeQuJPAcI5gG75NteYI2uqeN9dUUe9WkAJmRrgMCoToT+0Mdef7iBB8oQyAW8wk6HCHgitNuthZksN68MtidHcYJRSpdKObBr/Jz4vYEvm/cc/103hDDJbU7Zv63V3O5TWIQAFsKDvL1YfaZnUwOP08oG+3pe41U4DuPl/yEl4VlDDPaxKIThGWoYcCqLLMVYNrWymz5X8FgKpoFxsDgnhw9+96Qu/bH+2X0cBx+CMjHG6gLf4Kr+aS5gnlI33p5KELyIUKkQlFJlV1xRXb9yv0HAX/1J9Rg92icAHj8m5tb53C0lzcnNFcGJgeOqKSAWbxFcd1oqNqBAZW2Ljc66IJkynNzS9xz83oBXhteevF5lCTbuiRYrUGDx0Jwnpzd93Es3dI55m2IvNTb6JDw8Kb/NXmMCUsRlGoxaRyVXuMxhIfk5c3+XtxB20uuAWX7F33CFRXiKRCu4DXpiLcxVoC4RV0I3cwkYBT9tab4AcWT4fVIOFwLoFzMU3XdpU37pYZRKT5c7JOBwkhiGaHho8/gJh6pKxBl47shA5p8eEA2UQhWo6pxr+pWn+WUZBkeSAe/c9Dbvor5wE8=
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-firefox
- docker run -d -p4444:4444 selenium/standalone-firefox
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
