language: python
python:
- '3.8'
services:
- docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=secret.json
  - secure: G2wSotq5Bifdsi5oOi4g7QK+bDSgZs6Y9VyHLLJH2iYH5lIp6NiieWtPhWNp2CBYV+yRRERVnAQ4Am2Dgn24VnCZBFSjMrjCu7Gq0oT5RGfFDD8erbLty8fRxuaMSjt/fRt6TW2QpN4izNz2vCZ8pDRgj7SM7u78vli/ei0NQjGMBydDumQuuDIetmvjt2cdCR981uwU4PhDJm+VO3qfKSypvyXHbXfDzShrnGmPruTJyfkqnA0bZO52F8INYhvCSzqRrQ18PrptTfvQp+9uKlq3V1Ag5O9xLzoTDw7O7P5Aodi1ciWkFyuNycCSxlOyN/8H1Ngr/Ylm1FG7jTwxZwcrEQZMtk/YaJqEtx73yNEP2BfJNlrXNoUT/nhUmu+6JyvxwwtsnJGCz3BM8Kl5fzXaAGNMVEMTSQj46SBfS4NcMWFSXhoni9ODM3ygF8nnZUL0VfB6Sn4c6efWOdCDDHKPvRVBG14t0KoA//MnzVlVAO6wbfaVcp6HLrcLiiEmCzQETfQt+54yqS7pCx0Sh7ZDDqP8UT5WhLSUJElbqAErQbWphcawAxixRGjmLLemkbIWzKK8hMy6//p2Phmtlb0+krF8PqWYSKWS9p687moUSSSIwxgcH//q/s5aJdRLqcEg53QjU0XFVYcycoXxZHiajDKPqzLMk2I6f4kotp0=
  - secure: SiDrcczg1R+CJggKQ5d0K1109YQ5RigQpbjN6MK4B2AVtpiwMJTUUXjrj3NRUOcmtqBiLGlLXetqXqDaoSKOxV7lKkgdFg+Ht1v2Twu8jc0OZ0tatU6XNiS1CTr0HcKV9fBdQXuOoXMLY5Qg9oileOGznMuepps/l8mCkRpRhKTVKeJeej++CwA1sKHQ57m49Cf0FdM44J+grflENGsru+bG6XJjrbJzDRR+y7xr1ZxcNg5+KXpJMw1Q1a5nXabp9/68l/TO7HcfUI/JB5/2KjVFWNkXb3rDnb2xv7W8YeQ23+EEKMWSoC5dC2xIpWAmYyFJjhm/wzAYWyfdDle4nRLaaj/KK8ei92GGd8tzjUC6MmxHYWzqEn6dVqRVMborv0CMM69KmLJl9c+qrhG7kM9h/8r6YwrCgyFk+vOIPWv4EhT2AI04458yW5ga8gALG3teWv16jT5+73HQrlkVc9bqJTqx/xyY+E/c7h+gaHBwTW+zUw1agRh7l5HTkop3ZhgZ/CT069UtSDJHzrhE7CiEv/aHiwFp1zjmcfkLRUMy/PvsUtjrQxH4wzzyq9o6p6lS2RAQMlLT7fTdNsRr5sPNl4l6erB16ZTnkQqCLqw3ZrtNr8GmIkkECFF4n19J3o0eWt56gOYcb3ln99fTvPUfW0dUr3DLmL8z3Xpzxeo=
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv
  -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-firefox
- docker run -d -p4444:4444 selenium/standalone-firefox
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
