language: python
python:
- '3.8'
services:
- docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=secret.json
  - secure: NwTXWrmAgQ7RjXM3xcQGkbRtGqpmG/ZwRO+fLqmVZDkW07wjS0iroutKi1/ya9eLq3nNHLMUH8Fn15Qy+HIm8UncdSYbo2y4WS3hsYW1CzVxoe2tpQg2VitZcxJ3/+GAkZ1YkxxIY4cyZhOy14VFlWHFyTMOWGVkQ/p2R1xtVpmKsyqyLvEqwhN9Exi7KfvMnHVtc+SeqSBUmtiwvLzdXfaIP90v6aID8VD5WIjQwm5/IU8MVFHoI/Q0lAMwncgkmmR8sB+2ff8IyW+BvjUHJUMoukWtIv9C0nniKyE5OMexOrZPfc1Kevg9lpDR8DlXWHDp9HPOZRtC9cFz5N6D+H3gqstnubFPhHEtzEhKcLMq1+28BA0bSArKF3/kZYaJn3FuxteYkGYIgtlH0aUh9oJjn+fcoCU8DJPfb8r+o85AjM731WayUA6W3fp3cnvWtOPEP5MPUmGjS3Hzl581LbgndT0yuEbnwEScRMcFWUufDi3zXd5xJZTdUHAYNqXcxFOV0XYfvqyq9brSC5mkZP+ILnbHUNaM9IWj7YbYj/lwhUmWvq/xn0qoKVXLM4DgI+iU5USwKyLtTNrGUi60V1/ruqt4T+Tsakvy4qIqSkuJGkg89i1K+S1o6fm7HH07pntDj1oA8XU50G38dASeanNeea1TfANtaHy87ft2zlM=
  - secure: VX/JfQ/Vd0fAnUClknuHUFLrC9p3Udmm+Y9YKf8X2iz3wolb0vH1Zc25DstzQKA0twBYyIF/h1hbaP/gO1eOH55rgdQhAQUnhXeXkpdJ+cYTTDFw3HoqshxFQ074IX2not7GQtcTdEyPVy5Y0SqAhOp9xLO+nrauqyrgQqQxPiGCBMQiRw9Vme8IC+dQd7oztIta5FODYt6Go8WfdTd9+yJA93+gtHGinzO2dHvkxsMDITDjtI55Lwl1v4Y6ufb04guX2d4g7ZVt3u3W0kj0awCiK4DxvKWKOjZNVJBe4/4H3HT7tH2/eZQq5JaAjGYuWH2mO9QiMB4X7kItqzKtGjaDrrFqIjYw0Popr9oo+d/Ns0LJVHzLq4ocebTDZSHKSv0r2kW3AYvgEYk0r2XxowRhHsXFsqxV4zMOLhbTuzsYfjYAhrvwx+M1QcyFv/IXW335Rusk1oaUfG0vDquBTXkXcghpKTIPqxWj00FfNszIecrzhGsx5I7jYiO6MBI8CisI6Cry6gE8hY9h5CkM+OdebtmEfU56dC69wjo4tfey2hdXVM/5P/6X2j5pe9pdNN1wm8rjz03b61YD7/Inf73DJRxOwbwI07rlXExZgaoxcS3Kb0O9Z5K+ehieBW145x6ijJQUFGS4D9aRs1Y0ijLvXaR12L5trkWaegRF9BY=
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv
  -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-firefox
- docker run -d -p4444:4444 selenium/standalone-firefox
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
