language: python
python:
- '3.8'
services:
- docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=secret.json
  - secure: aYCiqD1E4NMmIjOLJxpQaLwdZ6LiZCFXVWXrT7QE9CbyERA/BB1tM84jIQPMyMf3tgfyX+sWxDVDvWtap6ozvn2z4dSPcid+AmUqsW2Whr98y56BFo6raVGAok6i170MPCCXFz6ts+HGYHVcgaZ4qmLY8Uelag7o86rdkb5ogFFJZPdsJ/Aq7j+K24cwoBPoeejGJQS1a8r2BUNHmWMS5eU6pD0iCdTH2NZOeIT81WIlF3hYVOEg71ghcUcnRevTcUQl/On2asQHlb7DU0mUZof7acKqZ8GxT6eM7eSTQhIqIbFevPQdT+0H7OR0SskUROLkYDtQOniMugku+Op34vSPIn3sjh8n9RRANJIofCno0XkrnoNGMICcTuQKVrCrLpHO9IQt+bDm79WPzLFk4rlXv5vupv0BLNbfAYfQo4lBU+c2Dun911kc6wKBd32V9Q9Gf6K77v+L9KSECbXKRmHEU535VLZDVGbkSaeADVOnuuTxhCjjPoOCcJeJKX8YlWwjtOFblDEu3MiEIX2z8zqflns2RHpEmG6I4YKdG8mB+o6gm1hkHHJwOOVoH1H9zUj+klwvMIwMKxc+WTfLPN+83ARey4R/cwGcBBiA+RAM/oCWZ63A19ZBA/1sfwgUoa61DDd/il2+Q9bCwItQ8+NmX+PhM4HrEGkNphUblaU=
  - secure: G2wSotq5Bifdsi5oOi4g7QK+bDSgZs6Y9VyHLLJH2iYH5lIp6NiieWtPhWNp2CBYV+yRRERVnAQ4Am2Dgn24VnCZBFSjMrjCu7Gq0oT5RGfFDD8erbLty8fRxuaMSjt/fRt6TW2QpN4izNz2vCZ8pDRgj7SM7u78vli/ei0NQjGMBydDumQuuDIetmvjt2cdCR981uwU4PhDJm+VO3qfKSypvyXHbXfDzShrnGmPruTJyfkqnA0bZO52F8INYhvCSzqRrQ18PrptTfvQp+9uKlq3V1Ag5O9xLzoTDw7O7P5Aodi1ciWkFyuNycCSxlOyN/8H1Ngr/Ylm1FG7jTwxZwcrEQZMtk/YaJqEtx73yNEP2BfJNlrXNoUT/nhUmu+6JyvxwwtsnJGCz3BM8Kl5fzXaAGNMVEMTSQj46SBfS4NcMWFSXhoni9ODM3ygF8nnZUL0VfB6Sn4c6efWOdCDDHKPvRVBG14t0KoA//MnzVlVAO6wbfaVcp6HLrcLiiEmCzQETfQt+54yqS7pCx0Sh7ZDDqP8UT5WhLSUJElbqAErQbWphcawAxixRGjmLLemkbIWzKK8hMy6//p2Phmtlb0+krF8PqWYSKWS9p687moUSSSIwxgcH//q/s5aJdRLqcEg53QjU0XFVYcycoXxZHiajDKPqzLMk2I6f4kotp0=
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv
  -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-firefox
- docker run -d -p4444:4444 selenium/standalone-firefox
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
