language: python
python:
- '3.8'
services:
- docker
addons:
  artifacts:
    paths:
    - $(ls /tmp/*.png | tr "\n" ":")
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=secret.json
  - secure: l2U9k5+3SUo0Vgxo7WZxIzUzJ+P0Ql1XcjB7BccHsQ0ghzFJv2/e+WQWwAbTJPaD3MKYTCc6+MA32kaMbXmQ1vYDwiDTdnOPsyGAN5UzBFMyodiO8Ytvwyk/Bz9fXKSk5mzMynOQPXXHnjPxwJGvK/rYeDAZ8H0LEHmRvpmMDhm5hgLa/ospA93XuPWyQljuHSYapHWjGehe41mqi53zaK9xvs08CnTbip772rzedq5qUOO/t2bJ3RfQFqpRp4S56vYj25fEvw3YImFQTsDpKPVnIfqbgYSKwa67KbS30cvib0+munV9yuWXjmORWWi92+nL8BNaaCaLmLhsUkCdf9hi8L9ZSeKNtv6qRjF4FFz+azEod+BZg7sJHP30kEC5Kctf1dGCulE4fLHJXRtMF2efJSp5sXmJuALdERSpJSDtVV5qoyertizMM98lBR00TcgHF1+FhaNJoE7Gv4F/NeRDiOEUjvzwp7JZGcRFIf0Xuzw19j40r0kNPUKmuTWU3pjLfvmmkXBBDj4TNGIXZmtpvayk+w/4V2+/t8ZGujfC+/qL0Sj55YF3DPNvNOy950M15Rj7hzorRkkd/qJJpUWfEnCO/q7xgnhTtbnZFCxI6sdaGcQxHxcIbMmMZxADMc3vHqfMeU2egkTszsjP7+naLuGweddxJkTEELSL8io=
before_install:
- openssl aes-256-cbc -K $encrypted_9fac4b6c837a_key -iv $encrypted_9fac4b6c837a_iv
  -in secret.json.enc -out secret.json -d
- docker pull selenium/standalone-firefox
- docker run -d -p4444:4444 selenium/standalone-firefox
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python main.py
